module.exports = {
  someSidebar: {
    "Getting Started": [
      'getting-started/curling-club-managers',
      'getting-started/pricing',
      'getting-started/premium',
      'getting-started/book-an-onboarding-session',
      'getting-started/support-and-feedback',
      'getting-started/faq',
      'getting-started/best-practices',
      'getting-started/referrals',
    ],
    "For Curlers": [
      'for-curlers/how-do-i-login',
      'for-curlers/google-login-without-gmail',
      'for-curlers/registering-for-a-league',
      'for-curlers/curler-profiles',
      'for-curlers/orders',
      'for-curlers/my-events',
      'for-curlers/teams',
      'for-curlers/waitlists',
      'for-curlers/sparing',
    ],
    "Club Management": [
      'club-management/website-hosting',
      'club-management/leagues',
      'club-management/programs',
      'club-management/products',
      'club-management/fees',
      'club-management/discounts',
      'club-management/calendar',
      'club-management/club-credits',
      'club-management/orders',
      'club-management/curlers',
      'club-management/waivers',
      'club-management/waitlists',
      'club-management/dashboard',
      'club-management/settings',
      'club-management/managers',
      'club-management/reports',
      'club-management/sponsors',
      'club-management/alerts',
      'club-management/custom-fields',
      'club-management/profile-fields',
      'club-management/linking-to-registration',
      'club-management/registration-widget',
      'club-management/support',
    ],
    "Event Management": [
      'event-management/registrations',
      'event-management/spares',
      'event-management/curlers',
      'event-management/teams',
      'event-management/round-robins',
      'event-management/playoff-brackets',
      'event-management/bracket-templates',
      'event-management/draw-schedule',
      'event-management/draw-schedule-templates',
      'event-management/scores',
      'event-management/event-managers',
    ],
    "Advanced Features": [
      'advanced/augmenting-curler-profiles',
    ],
    "Member Data": [
      'member-data/import',
      'member-data/setup',
    ],
    "API": [
      'api/items',
      'api/event-details',
      'api/product-details'
    ]
  },
};
