module.exports = {
  someSidebar: {
    "Getting Started": [
      'getting-started/overview',
      'getting-started/pricing',
      'getting-started/book-an-onboarding-session',
      'getting-started/support-and-feedback',
      'getting-started/faq',
    ],
    "For Curlers": [
      'for-curlers/how-do-i-login',
      'for-curlers/google-login-without-gmail',
      'for-curlers/registering-for-a-league',
      'for-curlers/curler-profiles',
      'for-curlers/sparing',
    ],
    "Club Management": [
      'club-management/dashboard',
      'club-management/leagues',
      'club-management/products',
      'club-management/fees',
      'club-management/discounts',
      'club-management/club-credits',
      'club-management/orders',
      'club-management/curlers',
      'club-management/reports',
      'club-management/custom-fields',
      'club-management/draw-schedule-templates',
      'club-management/managers',
      'club-management/waivers',
      'club-management/alerts',
      'club-management/settings',
      'club-management/website-hosting',
      'club-management/registration-widget',
    ],
    "Event Management": [
      'event-management/registrations',
      'event-management/spares',
      'event-management/curlers',
      'event-management/teams',
      'event-management/stages',
      'event-management/draw-schedule',
      'event-management/scores',
      'event-management/event-managers',
    ],
    "Advanced Features": [
      'advanced/augmenting-curler-profiles',
    ],
    // API: [
    //   'api/leagues',
    //   'api/competitions',
    //   'api/products',
    // ]
  },
};
